### ISSUE TITLE
Rakefile requires Ruby 2.0.0

### ISSUE THREAD

**Issue by numist** [numist/Switch#66]
@robrix reports:

```
Build: SwitchTests / Switch (Debug)
  Touch SwitchTests.xctest/Users/rob/Developer/Scraps/Switch/Scripts/commands/buildaction.rb:9:in `match': invalid byte sequence in US-ASCII (ArgumentError)
from /Users/rob/Developer/Scraps/Switch/Scripts/commands/buildaction.rb:9:in `create'
from /Users/rob/Developer/Scraps/Switch/Scripts/commands/command.rb:61:in `block (2 levels) in feed'
from /Users/rob/Developer/Scraps/Switch/Scripts/commands/command.rb:61:in `map'
from /Users/rob/Developer/Scraps/Switch/Scripts/commands/command.rb:61:in `block in feed'
from /Users/rob/Developer/Scraps/Switch/Scripts/commands/command.rb:59:in `map'
from /Users/rob/Developer/Scraps/Switch/Scripts/commands/command.rb:59:in `feed'
from Scripts/xcodebuild_prettify.rb:91:in `block in <main>'
from Scripts/xcodebuild_prettify.rb:90:in `each'
from Scripts/xcodebuild_prettify.rb:90:in `<main>'
rake aborted!
?  Shell command failed: set -e; set -o pipefail; xcodebuild -scheme "Switch" -project "Switch.xcodeproj" -derivedDataPath "/Users/rob/Developer/Scraps/Switch/DerivedData" test 2>&1 | Scripts/xcodebuild_prettify.rb
```

The Rakefile  requires ruby 2.0.0 or higher, so Switch should include an [`.rvmrc`](https://rvm.io/workflow/rvmrc) that ensures that an appropriate version of Ruby is used and any gem dependencies (like rake!) are installed.

**Comment by robrix** [comment]
Or just log something? I’m on system Ruby with `rake` and a few other gems installed; I don’t have `rvm`. Given that this is a deployment (rather than user) issue, may be able to get away with just logging “Ruby 2, please.”

**Comment by numist** [comment]
Good call. I committed a `.ruby-version` file, but detection and graceful exit is a good idea as well.
